### ISSUE TITLE
First load of comments slow

### ISSUE THREAD

**Issue by truongio** [davideast/hnpwa-firebase#12]
https://www.youtube.com/watch?v=uxxaSc8dYzk

> Page transitions don't feel like they block on the network

Doesn't load empty shell or anything on first load of comments on some threads. Subsequent loads of same comment section feels snappy.

Tested on two devices:

OnePlus 5
OxygenOS 4.5.6
Chrome 59.0.3071.125
Android 7.1.1

Macbook Pro 2016 (tried in normal and incognito mode)
macOS Sierra 10.12.6
Chrome Version 60.0.3112.78 (Official Build) (64-bit)

Internet speed
[http://beta.speedtest.net/result/6491159545.png](http://beta.speedtest.net/result/6491159545.png)

**Comment by davideast** [comment]
Hey @truongio! This is due to the "cold start" on Cloud Functions for Firebase. 

This app is hosting on a serverless infrastructure. Whenever someone visits the site the request first routes to a CDN edge. If the content is there, it returns quickly. If not, the request is routed to Cloud Functions where the content is dynamically generated. If there is no real traffic to the site, the Cloud Function will be shut off and will have to boot up. This is known as the cold start and it takes time. After the content is dynamically generated it is stored in the local CDN edge and then returned to the device.

This isn't an issue to worry about because of two reasons. 

First, this demo app receives no real traffic. If there was a real user base the function or CDN cache would be active.

Secondly, even when cold starts happen if only affects one user. The user who gets the cold start populates the CDN cache for the rest of the region. The rest of the users receive their response from the local edge which is extremely fast.
