### ISSUE TITLE
Infrastructural cost

### ISSUE THREAD

**Issue by Kasstorr** [davideast/hnpwa-firebase#16]
What's the cost of running this infrastructure?

**Comment by davideast** [comment]
Depends on traffic. The current levels fall within Firebase's free tier. I do have to enable billing to talk to the external network with Cloud Functions. The first [two million invocations](https://cloud.google.com/functions/pricing) per month are free. After two million it's just $0.0000004 per invocation. Since I use Firebase Hosting as a caching layer, it would take a ton of traffic to surpass 2 million invocations. The cache expiry is 10 minutes, so one visit in a CDN region will cache the content for 10 minutes in the area. Meaning it just takes one function invocation to serve many people.

There is a charge for Firebase Hosting since I'm no longer on the free plan. The storage cost is $0.026 per GB (I store < 1MB of data). The transfer rate cost is $0.15 per GB, and the home page size is usually under 20kb. Since the traffic is low, it's pretty cheap. Even if the traffic was high it would still be a dollar or two.
